name: Publish

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          registry-url: https://npm.pkg.github.com
          scope: '@janeapp'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish
        run: |
          cd dist
          npm publish
